server:
  port: 9001
  shutdown: graceful
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5


spring:
  application:
    name: catalog-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    username: user
    password: password
    url: jdbc:postgresql://localhost:5432/polardb_catalog
    hikari:
      connection-timeout: 2000
      maximum-pool-size: 5
  lifecycle:
    timeout-per-shutdown-phase: 15s

polar:
  greeting: Welcome Master!
